name: Weekly Tests

on:
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 UTC every Sunday
  workflow_dispatch:

jobs:
  get-lancedb-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch latest stable and 1 pre-release lancedb versions
        id: set-matrix
        run: |
          # Get all versions from PyPI
          pypi_versions=$(curl -s https://pypi.org/pypi/lancedb/json | jq -r '.releases | keys_unsorted | .[]')
          # Get all versions from Fury repository
          fury_versions=$(curl -s https://pypi.fury.io/lancedb/simple/lancedb/ | grep -o 'href="[^"]*"' | sed 's/href="//g' | sed 's/"//g' | grep -E '^lancedb-[0-9]+\.[0-9]+\.[0-9]+.*\.tar\.gz$' | sed 's/lancedb-//g' | sed 's/\.tar\.gz//g')

          # Combine and deduplicate versions
          all_versions=$(echo -e "$pypi_versions\n$fury_versions" | sort -u -V)

          # Get latest stable version
          stable_version=$(echo "$all_versions" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          # Get latest pre-release version (more specific pattern and better sorting)
          pre_version=$(echo "$all_versions" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+(a|b|rc|dev|alpha|beta)[0-9]*$' | sort -V | tail -n 1)

          # Create matrix array
          matrix_versions=()
          if [ -n "$stable_version" ]; then
            matrix_versions+=("$stable_version")
          fi

          if [ -n "$pre_version" ]; then
            matrix_versions+=("$pre_version")
          fi

          # Create JSON array manually
          json_array="["
          for i in "${!matrix_versions[@]}"; do
            if [ $i -gt 0 ]; then
              json_array="$json_array,"
            fi
            json_array="$json_array\"${matrix_versions[$i]}\""
          done
          json_array="$json_array]"

          matrix="{\"lancedb-version\": $json_array}"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  weekly-linux:
    needs: get-lancedb-versions
    name: "Weekly: Linux Python 3.12 (LanceDB ${{ matrix.lancedb-version }})"
    runs-on: ubuntu-24.04
    timeout-minutes: 300
    strategy:
      matrix: ${{ fromJson(needs.get-lancedb-versions.outputs.matrix) }}
    defaults:
      run:
        shell: bash
        working-directory: python
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Install protobuf
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: python
      - name: Install LanceDB
        run: |
          pip install "pydantic<2"
          pip install pyarrow==16
          pip install --extra-index-url https://pypi.fury.io/lancedb/ -e .[tests]
          pip install --extra-index-url https://pypi.fury.io/lancedb/ lancedb==${{ matrix.lancedb-version }}
      - name: Run weekly tests
        run: pytest -m "weekly" -svv --durations=300 python/tests
      - name: Upgrade LanceDB
        run: |
          pip install -e .[tests]
      - name: Run weekly tests again
        run: pytest -m "weekly" -svv --durations=300 python/tests
